[package]
name = "jfec"
version = "0.1.0"
authors = ["Artem Alekseev fexolm@gmail.com"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
itertools = "0.8.0"
llvm-sys = "70.0.0"

[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "create_ast"
harness = false